### ISSUE TITLE
how to build the app

### ISSUE THREAD

**Issue by KebabLord** [Superjo149/auryo#265]
Instead of installing from preinstalled packages, i want to install auryo from the source that i made changes on. How to build the app from source? using debian 10

**Comment by KebabLord** [comment]
i did
```
sudo yarn install
sudo yarn run package:linux
```
got this:
```
  ⨯ Application entry file "dist/electron/main.js" in the "/home/owo/Github/auryo/build/release/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
Error: Application entry file "dist/electron/main.js" in the "/home/owo/Github/auryo/build/release/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
at error (/home/owo/Github/auryo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
at checkFileInArchive (/home/owo/Github/auryo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
at LinuxPackager.checkFileInPackage (/home/owo/Github/auryo/node_modules/app-builder-lib/src/platformPackager.ts:402:7)
at LinuxPackager.sanityCheckPackage (/home/owo/Github/auryo/node_modules/app-builder-lib/src/platformPackager.ts:453:5)
at LinuxPackager.doPack (/home/owo/Github/auryo/node_modules/app-builder-lib/src/platformPackager.ts:242:5)
at LinuxPackager.pack (/home/owo/Github/auryo/node_modules/app-builder-lib/src/platformPackager.ts:114:5)
at Packager.doBuild (/home/owo/Github/auryo/node_modules/app-builder-lib/src/packager.ts:444:9)
at executeFinally (/home/owo/Github/auryo/node_modules/app-builder-lib/node_modules/builder-util/src/promise.ts:12:14)
at Packager._build (/home/owo/Github/auryo/node_modules/app-builder-lib/src/packager.ts:373:31)
at Packager.build (/home/owo/Github/auryo/node_modules/app-builder-lib/src/packager.ts:337:12)
at executeFinally (/home/owo/Github/auryo/node_modules/app-builder-lib/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by KebabLord** [comment]
also tried building with tsc
```
λ tsc
node_modules/lastfm/typings/index.d.ts:9:44 - error TS1016: A required parameter cannot follow an optional parameter.

9     public request(method?: LastfmMethods, params: any): any;
                                             ~~~~~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:23:18 - error TS2345: Argument of type 'false' is not assignable to parameter of type 'SetStateAction<undefined>'.

23     setIsSeeking(false);
                    ~~~~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:30:17 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'SetStateAction<undefined>'.

30     setNextTime(to);
                   ~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:31:18 - error TS2345: Argument of type 'true' is not assignable to parameter of type 'SetStateAction<undefined>'.

31     setIsSeeking(true);
                    ~~~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:40:22 - error TS2345: Argument of type 'true' is not assignable to parameter of type 'SetStateAction<undefined>'.

40         setIsSeeking(true);
                        ~~~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:60:53 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

60       <div className={styles.time}>{getReadableTime(isSeeking ? nextTime : currentTime, false, true)}</div>
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 6 errors.
```

**Comment by KebabLord** [comment]
Successfully builded with
```
yarn install
yarn run release:linux
```
while compiling for arch with pacman it throw errors but successfully compiled my deb to `build/release/auryo_2.5.3_amd64.deb`

**Comment by KebabLord** [comment]
did
```
yarn install
tcs // compiled modified typescript codes
yarn run build
yarn run package:linux
```
the funny part is typescript compiler throws errors on even fresh repository
```
owo@junicchi~/Github/auryo:
λ tsc
node_modules/lastfm/typings/index.d.ts:9:44 - error TS1016: A required parameter cannot follow an optional parameter.
9     public request(method?: LastfmMethods, params: any): any;
                                             ~~~~~~
src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:23:18 - error TS2345: Argument of type 'false' is not assignable to parameter of type 'SetStateAction<undefined>'.
23     setIsSeeking(false);
                    ~~~~~
src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:30:17 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'SetStateAction<undefined>'.
30     setNextTime(to);
                   ~~
src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:31:18 - error TS2345: Argument of type 'true' is not assignable to parameter of type 'SetStateAction<undefined>'.
31     setIsSeeking(true);
                    ~~~~
src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:40:22 - error TS2345: Argument of type 'true' is not assignable to parameter of type 'SetStateAction<undefined>'.
40         setIsSeeking(true);
                        ~~~~
src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:60:53 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.
60       <div className={styles.time}>{getReadableTime(isSeeking ? nextTime : currentTime, false, true)}</div>
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 6 errors.
```

**Comment by Superjo149** [comment]
You can read the development contributing guide to get started with Auryo. https://github.com/Superjo149/auryo/blob/master/.github/DEVELOPMENT.md
