### ISSUE TITLE
auryo hanging on startup (linux)

### ISSUE THREAD

**Issue by NeoGeetz** [Superjo149/auryo#278]
First off awesome application, I was able to use it yesterday for the first time and it's excellent, well designed and all.

unfortunately I'm not able to use it today, but at least there is some stuff it printed that might help in debugging. I've tried uninstalling and reinstalling the package and logging out of soundcloud on other devices to no effect.

running in arch linux (installed the pre-compiled auryo-bin package version 2.5.3), typical 64bit x86 processor laptop.
I can provide any more specific environment info if needed.

--------------------------------
HOME]$ auryo
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[1589213702461] INFO : App started
[1589213704617] ERROR: Request failed with status code 403
    Error: Request failed with status code 403
        at createError (/opt/Auryo/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/opt/Auryo/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/opt/Auryo/resources/app.asar/node_modules/axios/lib/adapters/http.js:236:11)
        at IncomingMessage.emit (events.js:215:7)
        at IncomingMessage.EventEmitter.emit (domain.js:476:20)
        at endReadableNT (_stream_readable.js:1183:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)
[1589213708661] ERROR: Error with mqtt
(electron) 'isClosable function' is deprecated and will be removed. Please use 'closable property' instead.
[1589213708672] ERROR: Disconnected from mqtt
    Error: Disconnected from mqtt
        at e.<anonymous> (/opt/Auryo/resources/app.asar/dist/electron/webpack:/src/main/aws/awsIotService.ts:58:16)
        at step (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:136:27)
        at Object.next (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:117:57)
        at /opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:110:75
        at new Promise (<anonymous>)
        at Object.__awaiter (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:106:16)
        at DeviceClient.<anonymous> (/opt/Auryo/resources/app.asar/dist/electron/webpack:/src/main/aws/awsIotService.ts:57:31)
        at DeviceClient.emit (events.js:210:5)
        at DeviceClient.EventEmitter.emit (domain.js:476:20)
        at MqttClient.<anonymous> (/opt/Auryo/resources/app.asar/node_modules/aws-iot-device-sdk/device/index.js:791:12)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'Symbol(pino.nestedKey)' of undefined
    at LOG (/opt/Auryo/resources/app.asar/node_modules/pino/lib/tools.js:37:15)
^C
HOME]$ exit
exit

Script done on 2020-05-11 10:07:46-07:00 [COMMAND_EXIT_CODE="130"]
--------------------------------------------------------
(it hangs on this animation VV)
![Screenshot from 2020-05-11 11-35-49](https://user-images.githubusercontent.com/16139535/81752714-e521e400-9466-11ea-91b0-555def86cf8e.png)

**Comment by NeoGeetz** [comment]
Ok, now My issue has changed to the same as a different issue posted by a different user.
Should I close this issue ? What I can say has changed is, my hardware clock was 4 hours behind earlier this morning, (ran hwclock to fix it) and I've been installing some packages today to set up fightcade (just mentioning as only major changes to my system over the course of the day).

**Comment by RealAct** [comment]
I'm also being unable to login to the service in Linux, I receive a slightly different message:
Something went wrong
Request failed with status code 405

I attached a screenshot, hope it can be fixed soon, I love this app :-(

![screenshot](https://user-images.githubusercontent.com/8281482/82154489-5cc38a80-983c-11ea-9d1e-c153a689a010.png)

**Comment by Superjo149** [comment]
Please see #276
