### ISSUE TITLE
Something went wrong during login [Error with mqtt]

### ISSUE THREAD

**Issue by KebabLord** [Superjo149/auryo#297]
# 🐛 Bug report

just installed auryo on a fresh devuan setup. after clicking login button browser-window doesn't come.
![err](https://user-images.githubusercontent.com/24779257/90012409-53965e00-dc71-11ea-95e3-31e677388599.png)

```
[1597258386493] ERROR: Error with mqtt
[1597258386520] ERROR: Disconnected from mqtt
    Error: Disconnected from mqtt
        at e.<anonymous> (/opt/Auryo/resources/app.asar/dist/electron/webpack:/src/main/aws/awsIotService.ts:58:16)
        at step (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:136:27)
        at Object.next (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:117:57)
        at /opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:110:75
        at new Promise (<anonymous>)
        at Object.__awaiter (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:106:16)
        at DeviceClient.<anonymous> (/opt/Auryo/resources/app.asar/dist/electron/webpack:/src/main/aws/awsIotService.ts:57:31)
        at DeviceClient.emit (events.js:210:5)
        at DeviceClient.EventEmitter.emit (domain.js:476:20)
        at MqttClient.<anonymous> (/opt/Auryo/resources/app.asar/node_modules/aws-iot-device-sdk/device/index.js:791:12)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Disconnected from mqtt
    at e.<anonymous> (/opt/Auryo/resources/app.asar/dist/electron/webpack:/src/main/aws/awsIotService.ts:58:16)
    at step (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:136:27)
    at Object.next (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:117:57)
    at /opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/opt/Auryo/resources/app.asar/node_modules/tslib/tslib.js:106:16)
    at DeviceClient.<anonymous> (/opt/Auryo/resources/app.asar/dist/electron/webpack:/src/main/aws/awsIotService.ts:57:31)
    at DeviceClient.emit (events.js:210:5)
    at DeviceClient.EventEmitter.emit (domain.js:476:20)
    at MqttClient.<anonymous> (/opt/Auryo/resources/app.asar/node_modules/aws-iot-device-sdk/device/index.js:791:12)
```

#### Which version of Auryo? 
latest release.

**Comment by KebabLord** [comment]
that's the full nodejs debug i got from my own yarn build of auryo
[debug.log](https://github.com/Superjo149/auryo/files/5144938/debug.log)

**Comment by KebabLord** [comment]
### finally solved
Although there is no trace on log and errors about if the error is SSL, I manually added soundcloud's root certificates to my system, reconfigured auryo and it started working again.
```
#Get soundcloud's root certificates
openssl s_client -showcerts -verify 5 -connect soundcloud.com:443 < /dev/null | awk '/BEGIN/,/END/{ if(/BEGIN/){a++}; out="cert"a".crt"; print >out}' && for cert in *.crt; do newname=$(openssl x509 -noout -subject -in $cert | sed -n 's/^.*CN=\(.*\)$/\1/; s/[ ,.*]/_/g; s/__/_/g; s/^_//g;p').crt; mv $cert $newname; done
#Copy the generated two files to your ca-certificates folder
mv *.crt /usr/local/share/ca-certificates
sudo dpkg-reconfigure ca-certificates
sudo dpkg-reconfigure auryo
```
